apiVersion: v1
kind: Pod
metadata:
  name: nginx-app
  labels:
    name: nginx-app
spec:
  containers:
  - name: nginx-app
    image: adityashahi/myapp
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 30080

---
  
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: nginx-app
  ports:
  - port: 80
    targetPort: 30080
