---
apiVersion: v1
kind: Pod
metadata:
  name: beer-review-pod
  labels:
    name: beer-review-front-end
    stack: dev
spec:
  containers:
  - name: beer-review
    image: adityashahi/myapp:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    name: beer-review-front-end
  ports:
  - protocol: TCP
    port: 80
    nodePort: 30080
  type: NodePort
